# Generated by Django 5.0.9 on 2024-10-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('cnic', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('github_url', models.URLField(null=True)),
                ('participant_type', models.CharField(choices=[('PROFESSIONAL', 'PROFESSIONAL'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=50)),
                ('ambassador_name', models.CharField(max_length=255, null=True)),
                ('participant_status', models.CharField(choices=[('PENDING', 'PENDING'), ('SHORTLISTED', 'SHORTLISTED'), ('CONFIRMED', 'CONFIRMED'), ('ATTENDED', 'ATTENDED')], default='PENDING', max_length=20)),
                ('payment_acknowledgement', models.BooleanField(default=False)),
            ],
        ),
    ]
