# Generated by Django 5.0.9 on 2024-10-10 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gdg_events', '0001_initial'),
        ('gdg_participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('workshop_participation', models.JSONField(null=True)),
                ('team_name', models.CharField(max_length=255, null=True)),
                ('team_members', models.JSONField(null=True)),
                ('purpose_of_participation', models.TextField(null=True)),
                ('google_technologies', models.JSONField(null=True)),
                ('previous_projects', models.TextField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdg_events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdg_participants.participant')),
            ],
        ),
    ]
