services:
  docs:
    image: gdg-registration-backend_local_docs
    container_name: gdg-registration-backend_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./gdg-registration-backend:/app/gdg-registration-backend:z
    ports:
      - '9000:9000'
    command: /start-docs
