# Generated by Django 5.0.9 on 2024-10-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdg_participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='job_role',
            field=models.CharField(max_length=2550, null=True),
        ),
    ]
