log:
  level: INFO

entryPoints:
  web:
    # http
    address: ':80'
    http:
      # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ':443'

certificatesResolvers:
  letsencrypt:
    # https://doc.traefik.io/traefik/https/acme/#lets-encrypt
    acme:
      email: 'hellogdgkolachi@gmail.com'
      storage: /etc/traefik/acme/acme.json
      # https://doc.traefik.io/traefik/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: 'Host(`devfest.gdgkolachi.com`) && PathPrefix(`/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    web-static-router:
      rule: 'Host(`devfest.gdgkolachi.com`) && PathPrefix(`/static/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-static
      tls:
        certResolver: letsencrypt

    web-media-router:
      rule: 'Host(`devfest.gdgkolachi.com`) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    django-static:
      loadBalancer:
        servers:
          - url: http://django:5000  # Django should serve static files here

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80  # Nginx should serve media files here

