log:
  level: INFO

entryPoints:
  # HTTP entry point
  web:
    address: ':80'
    http:
      redirections:
        # Redirect HTTP traffic to HTTPS
        entryPoint:
          to: web-secure

  # HTTPS entry point
  web-secure:
    address: ':443'

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'hellogdgkolachi@gmail.com'
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    # Main router for the Django application (serves the main app)
    web-secure-router:
      rule: 'Host(`devfest.gdgkolachi.com`) && PathPrefix(`/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    # Router for serving static files
    web-static-router:
      rule: 'Host(`devfest.gdgkolachi.com`) && PathPrefix(`/static/`)'
      entryPoints:
        - web-secure
      service: django-static  # Static files are served by Django
      tls:
        certResolver: letsencrypt

    # Router for serving media files (using Nginx or Django)
    web-media-router:
      rule: 'Host(`devfest.gdgkolachi.com`) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      service: django-media  # Assuming Nginx or a dedicated service for media
      tls:
        certResolver: letsencrypt

  # Middleware for CSRF protection
  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  # Services definition
  services:
    # Django service to handle application requests
    django:
      loadBalancer:
        servers:
          - url: http://django:5000  # Django is running on port 5000 in Docker

    # Django static service to serve static files (handled by Django)
    django-static:
      loadBalancer:
        servers:
          - url: http://django:5000  # Static files should be served from Django itself

    # Nginx service to handle media files (change if needed)
    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80  # Nginx should serve media files

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
